PARTICIPANTS: use this file for creating the remove book from catalog diagram in mastery task 01
@startuml
RemoveBookFromCatalogActivity -> RemoveBookFromCatalogResponse: execute

CatalogDao <- RemoveBookFromCatalogActivity: removeBookFromCatalog
RemoveBookFromCatalogResponse -> BookNotFoundException


@enduml
